### PR TITLE
Move Images to CDN

### PR DESCRIPTION
**Pull request by jexp**

### CODE REVIEW

**Review by Mogztter — APPROVED** [review]
LGTM :+1: 

And the mixed content issue is fixed on Netlify :tada:

**Comment by jexp** [comment]
@Mogztter 

for KB shouldn't these be handled by a default image prefix?image:https://s3.amazonaws.com/dev.assets.neo4j.com/kb-content/a-lightweight-approach-to-testing-the-neo4j-rest-api-with-authentication-qq4KTt1.png[image]

**Comment by Mogztter** [comment]
> for KB shouldn't these be handled by a default image prefix?`image:https://s3.amazonaws.com/dev.assets.neo4j.com/kb-content/a-lightweight-approach-to-testing-the-neo4j-rest-api-with-authentication-qq4KTt1.png[image]`

That's a good point!
Now that all images are stored in the same place, we can define `:imagesdir: https://s3.amazonaws.com/dev.assets.neo4j.com/kb-content` in the `build.gradle` and remove the suffix in all the articles, for instance: `image:a-lightweight-approach-to-testing-the-neo4j-rest-api-with-authentication-qq4KTt1.png[]`.

But I would rather do that in another pull request.
Once this is done, we should document this change in the `README.adoc`, add an example in the `template.adoc` and @viveksaran71 should probably add a note in the authoring documentation.

**Comment by jexp** [comment]
Yes to all. If possible I’d do it all in one go.

**Comment by Mogztter** [comment]
@jexp I've updated https://github.com/neo4j-documentation/knowledge-base/pull/55
Antora does not allow to override the value of the built-in `imagesdir` attribute so I'm using `:assets-cdn: https://s3.amazonaws.com/dev.assets.neo4j.com/kb-content` and images should be declared as:

```
image::{assets-cdn}/shared-lock.png[Shared Lock]
```

**Pull request closed without merging**
